'use strict';
(() => {
  const el=id=>document.getElementById(id), esc=value=>String(value??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const copy={en:{compareTitle:'Measured diagnosis advantage',compareBody:'Installed Rerun 0.38.1 CLI correctly found one unequal episode chunk. Sentinel identified step 4, camera 2, equal action and preceding feedback, then linked both source frames in the same workflow. This compares these actual workflows, without a cross-tool speed claim.',nav:'Execution diff',kicker:'VERIFIED EXECUTION DIFF',title:'Find the first change. Open its evidence.',lead:'Compare two independently keyed VLA records in the App or CLI. Align task, state, seed and instruction; separate action, feedback, cursor, outcome and expected authorization changes.',actions:'identical final actions',observations:'camera feedback difference',auth:'episodes with expected authorization-mode changes',select:'Inspect every paired episode',jump:'Jump to first difference',timeline:'Recorded execution step',reset:'Reset views',left:'Reference · baseline',right:'Candidate · active',scope:'This web demo displays the saved derived report and a subset of original poses. The App/CLI reverify signatures and recompute the comparison. At step 4, both recordings retain the action and camera fingerprints but no body pose; the 3D reference is explicitly step 0. Later saved poses can be inspected on the timeline.',download:'Download complete 40-episode report',workflow:'CLI workflow and measured comparison',equal:'No unexpected difference in this paired episode.',found:'First difference: camera 2 feedback, step 4. Final action bytes and previous feedback match; the other recorded state fingerprints match.',details:'View exact fields and source references',summary:'actions / feedback / cursor / outcome / unexpected authorization differences',pose:'Action and feedback step',exact:'Both 3D views show the exact recorded pose.',prior:'No body pose was retained at this step. Both 3D views show the preceding saved pose at step',fail:'Saved comparison unavailable',motion:'The 3D timeline is available for the episode with the recorded feedback difference.'},zh:{compareTitle:'已经实测的诊断优势',compareBody:'实际安装的 Rerun 0.38.1 CLI 正确检测出一个 Episode chunk 不同。Sentinel 进一步定位第 4 步、第二路相机，说明动作及前一步反馈一致，并在同一工作流链接两侧源帧。这里比较本次实际工作流，不主张跨工具提速。',nav:'执行差异',kicker:'已验签执行差异诊断',title:'找到第一次变化，直达它的证据。',lead:'在 App 或 CLI 中比较两份分别选择公钥的 VLA 记录。按任务、初态、种子和指令对齐；分别检查动作、反馈、游标、结果与预期授权变化。',actions:'最终动作字节一致',observations:'相机反馈差异',auth:'发生预期授权模式变化的样本',select:'检查全部配对 Episode',jump:'定位首个差异',timeline:'保存的执行步',reset:'重置视角',left:'参考运行 · baseline',right:'待检查运行 · active',scope:'此网页展示保存的派生报告与原始姿态子集。App/CLI 会重新验签并重算比较。第 4 步两份记录保存了动作和相机指纹，但没有 body 姿态，三维参考明确标为第 0 步。可拖动时间轴检查后续保存的运动。',download:'下载完整 40 组诊断报告',workflow:'CLI 使用方法与实际对照结果',equal:'这组配对没有发现非预期差异。',found:'首个差异：第 4 步的第二路相机反馈。最终动作字节和前一步反馈一致，其他已记录状态指纹一致。',details:'查看具体字段与源记录引用',summary:'动作 / 反馈 / 游标 / 结果 / 非预期授权差异',pose:'动作与反馈步',exact:'两侧三维均为当前步的精确保存姿态。',prior:'当前步没有保存 body 姿态；两侧三维显示此前保存的姿态，步',fail:'无法读取保存的比较报告',motion:'这条三维时间轴对应发现反馈差异的 Episode。'}};
  let locale=document.body.lang==='zh'?'zh':'en',report=null,projection=null,viewers=null,row=null,step=4,generation=0;
  const t=k=>copy[locale][k];
  async function checked(path,hash,gzip=false) {
    const response=await fetch(path);if(!response.ok)throw new Error(`HTTP ${response.status}`);
    const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.length>32*1024*1024)throw new Error('Asset exceeds limit');
    const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(digest!==hash)throw new Error('Asset fingerprint mismatch');
    const decoded=gzip?await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer():bytes;
    return JSON.parse(new TextDecoder().decode(decoded));
  }
  function translate(){document.querySelectorAll('[data-diff-copy]').forEach(n=>n.textContent=t(n.dataset.diffCopy));if(report)renderRow();}
  function draw(){if(!viewers)return;const frame=projection.left.frames[step];if(!frame)return;viewers.forEach(v=>v.draw(step));el('diffTimeline').value=String(step);let pose=step;while(pose>0&&!projection.left.frames[pose].bodyWorldPosition?.length)pose--;
    el('diffPose').textContent=`${t('pose')} ${frame.step} · ${pose===step?t('exact'):`${t('prior')} ${projection.left.frames[pose].step}。`}`;
  }
  async function motion(){if(viewers){draw();return;}const current=++generation;
    const [model,frames]=await Promise.all([checked('assets/native-v3-panda-task0.json.gz','7c5b1e507c3f7b75032fe0440ec88da84f18b3b76ac2a81654eac7131964ebf4',true),checked('assets/execution-diff-frames.json','6e2f02a79df93f2049bd35a5a8792d5fc84e3f4f8a658b9e240ced9e4d2a0246')]);if(current!==generation)return;
    projection=frames;viewers=[new window.SentinelNativeViewer(el('diffLeft')),new window.SentinelNativeViewer(el('diffRight'))];
    viewers[0].setRecord(model,frames.left);viewers[1].setRecord(model,frames.right);el('diffTimeline').max=String(frames.left.frames.length-1);draw();
  }
  function renderRow(){row=report.episodes[Number(el('diffEpisode').value)||0];const c=row.counts,d=row.first_difference;
    el('diffCell').textContent=`${t('summary')}: ${c.action} / ${c.observation} / ${c.cursor} / ${c.outcome} / ${c.authorization} · ${c.compared_actions} actions`;
    el('diffDetails').innerHTML=`<div class="diff-cell-detail"><strong>${d?t('found'):t('equal')}</strong><p>${esc(row.key.instruction)}</p>${d?`<details><summary>${t('details')}</summary><pre>${esc(JSON.stringify(d,null,2))}</pre></details>`:''}</div>`;
    const show=d&&row.key.task_id===0&&row.key.initial_state_index===48;el('diffMotion').hidden=!show;
    if(show)motion().catch(e=>{el('diffPose').textContent=`${t('fail')}: ${e.message}`;});
  }
  el('diffEpisode').onchange=()=>{step=4;renderRow();};el('diffFirst').onclick=()=>{step=4;draw();};el('diffTimeline').oninput=e=>{step=Number(e.target.value);draw();};el('diffReset').onclick=()=>viewers?.forEach(v=>v.reset());
  window.addEventListener('sentinel-language',e=>{locale=e.detail?.locale==='zh'?'zh':'en';translate();});translate();
  checked('assets/execution-diff-report.json','4cf539abe206a733707f69c79df2cebf435cbaf4a6546475e1d3fb5c6bc840d4').then(value=>{report=value;el('diffEpisode').innerHTML=value.episodes.map((r,i)=>`<option value="${i}">Task ${esc(r.key.task_id)} · state ${esc(r.key.initial_state_index)} · ${r.first_difference?'Δ':'='} · ${r.counts.compared_actions} actions</option>`).join('');el('diffEpisode').value=String(value.episodes.findIndex(r=>r.first_difference));el('diffEpisode').disabled=false;renderRow();}).catch(e=>el('diffCell').textContent=`${t('fail')}: ${e.message}`);
})();
